FROM python:3.9-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# Sao chép toàn bộ code của bạn vào container
COPY ./ /app/

# Mở port 7860 (port mặc định của Hugging Face Spaces)
EXPOSE 7860

# Lệnh để chạy ứng dụng khi container khởi động
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7860"]